"""create tables

Revision ID: a31057473601
Revises: 
Create Date: 2025-05-15 20:21:21.248895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a31057473601'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('soldiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('rank', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('handguns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('solidier_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['solidier_id'], ['soldiers.id'], name=op.f('fk_handguns_solidier_id_soldiers')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_table('machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('serial_number', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('soldier_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['soldier_id'], ['soldiers.id'], name=op.f('fk_machines_soldier_id_soldiers')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_table('soldier_team',
    sa.Column('soldier_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['soldier_id'], ['soldiers.id'], name=op.f('fk_soldier_team_soldier_id_soldiers')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_soldier_team_team_id_teams')),
    sa.PrimaryKeyConstraint('soldier_id', 'team_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('soldier_team')
    op.drop_table('machines')
    op.drop_table('handguns')
    op.drop_table('teams')
    op.drop_table('soldiers')
    # ### end Alembic commands ###
